[DPE-3024] Add badges to README.md
canonical/spark-rock pull request #61
Opened 2023-12-05 09:56 UTC by deusebio

2023-12-05 13:46 UTC, welpaolo submitted a review, later dismissed

2023-12-12 08:59 UTC, theoctober19th requested changes

2023-12-12 08:59 UTC, theoctober19th commented on README.md
> +[![Container Registry](https://img.shields.io/badge/Container%20Registry-published-blue)](https://github.com/canonical/charmed-spark-rock/pkgs/container/charmed-kafka)
The link redirects to Charmed Kafka. Shouldn't this be https://github.com/canonical/charmed-spark-rock/pkgs/container/charmed-spark instead?

2023-12-12 10:41 UTC, theoctober19th approved these changes

2023-12-12 10:55 UTC, welpaolo approved these changes

2023-12-12 14:17 UTC, merged